fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: '0.4.0'
  symlinks:
    nfs: "#{source_dir}"
