fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 3.2.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: '0.4.0'
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: 'v1.0.2'
    create_resources: git://github.com/puppetlabs/puppetlabs-create_resources.git  
  symlinks:
    nfs: "#{source_dir}"
