fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.1.2
    augeasproviders_core:
      repo: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: git://github.com/hercules-team/augeasproviders_shellvar.git
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.1.3
  symlinks:
    nfs: "#{source_dir}"
