fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.1.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: '0.4.2'
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: 'v1.0.2'
    inifile:
      repo: git://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.0.1
    infiniband: git://github.com/treydock/puppet-infiniband.git
  symlinks:
    nfs: "#{source_dir}"
